stages:
  - build
  - test
  - publish

image: maven:adoptopenjdk

# Build Phase
# ===========
build_phase:
  variables:
    SPRING_PROFILE_ACTIVE: prod
    PROD_DB_URL: jdbc:postgresql://ec2-44-198-151-32.compute-1.amazonaws.com:5432/d73v1h3l34pjpn?reWriteBatchedInserts=true
    PROD_DB_USER: hfzgpccbpfnnkz
    PROD_DB_PASSWORD: cd0f8333703f493cd039fc15065564441fb76ede643d8728e151e33f7ea72127
  stage: build
  before_script:
    - mvn clean
  script:
    - mvn install
  artifacts:
    paths:
      - target/doc-0.0.1-SNAPSHOT.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .mvn
      - target
  only:
    - master


# Test Phase
# ==========
#test_phase:
#  stage: test
#  image: trion/ng-cli-karma:9.0.1
#  allow_failure: false
#  script:
#    - ng test --progress=false --watch=false
#  cache:
#    policy: pull
#    key: "$CI_COMMIT_REF_NAME"
#    paths:
#      - dist
#      - node_modules
#  only:
#    - master

# Publish Phase
# =============
publish_phase:
  stage: publish
  before_script:
    - echo $DOCKER_REPO_PASSWORD | docker login --username $DOCKER_REPO_USERNAME --password-stdin
  image: docker:git
  services:
    - docker:19.03.5-dind
  script:
    - docker build -t $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:doc .
    - docker push $DOCKER_REPO_USERNAME/$DOCKER_REPO_NAME:doc
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .mvn
      - target
